Incorporando la funcionalidad de poder cargar valores a la memoria. E…
Orga-UNQ/qsim pull request #7
Opened 2016-08-29 19:55 UTC by susanrosito

…l archivo input.json ahora tiene una seccion mas, que nos permite poder cargar valores

2016-08-29 22:08 UTC, faloi commented on src/test/scala/ar/edu/unq/tpi/qsim/arq/CicloEjecucionArquitecturaQ3.scala
> +    var posMemory = Map[String, java.util.Map[String, String]]()
¿Por qué se agregó este `java.util` por todos lados?

2016-08-29 22:12 UTC, susanrosito commented on src/test/scala/ar/edu/unq/tpi/qsim/arq/CicloEjecucionArquitecturaQ3.scala
> +    var posMemory = Map[String, java.util.Map[String, String]]()
No se porque tiene un bug el metodo tojson de gson cuando le pasas un Map de tipo scala.collection.mutuable.Map, aparentemente no lo puede parsear bien, porque te devuelve un map vacio. Probe con el tipo java y funciono.

2016-08-29 22:16 UTC, faloi commented on src/main/resources/input.json
> +  	  "0000": "1234"
No me quedó claro al final qué son estos dos niveles... ¿fila y columna?

2016-08-29 22:19 UTC, susanrosito commented on src/main/resources/input.json
> +  	  "0000": "1234"
exacto, para que sepas en que columna estas de la fila, aunque se podría poner dentro de una lista, sabiendo que las posiciones contienen su respectivo valor de cada fila, osea cambiar columna explicita, por implícita, reemplazada por la posición de la lista. 
(Esto ultimo lo veo como mejora)

2016-08-29 22:25 UTC, faloi commented on src/main/resources/input.json
> +  	  "0000": "1234"
No, para mí eso que decís es aún más confuso. Me gustaría que opine @huenu acá, pero yo creo que sería más intuitivo no tener esa anidación, por ejemplo así:

```json
{
  "0000x0001": "FA32",
  "0000x002A": "1400",
}
````

2016-08-29 22:29 UTC, susanrosito commented on src/main/resources/input.json
> +  	  "0000": "1234"
hmm bueno, eso seria filaxcolumna : valor no? 
Esta buena la idea, bueno si quieres lo hablamos en nuestro grupo de whatsapp

2016-08-29 22:30 UTC, faloi commented on src/main/resources/input.json
> +  	  "0000": "1234"
Prefiero hablarlo por acá, así queda documentada la discusión. :smile_cat:

2016-08-29 22:33 UTC, susanrosito commented on src/main/resources/input.json
> +  	  "0000": "1234"
la invito entonces :)

2016-09-02 16:59 UTC, huenu commented on src/main/resources/input.json
> +  	  "0000": "1234"
Hola compañeros. Me parece mas practico enumerar contenido por bloque de celdas (el otro día le comenté a Su pero muy en el aire, y luego me quedé regulando). Por ejemplo:

{
  "000":{ "FA32","0000","0000","0000","FA32","0000","0000","0000","FA32","0000","0000","0000","FA32","0000","0000","0000"}
}
En este ejemplo, se cargan las celdas desde 0000 hasta 000F

Otra opcion es cargar celdas especificas:

{
 "0000":"FA32",
 "0005":"FA32"
}

¿Que les parece?

2016-09-02 17:08 UTC, faloi commented on src/main/resources/input.json
> +  	  "0000": "1234"
A mí me resulta mucho más intuitiva la segunda, me ahorra de cargar celdas que no me interesan. De todos modos, todavía tenemos que decidir entre estas dos opciones:

```js
// Opción 1
{
  "0000x0001": "FA32",
  "0000x002A": "1400",
  "0001x0003": "1984",
}

// Opción 2
{
  "0000": {
    "0001": "FA32",
    "002A": "1400"
  },
  "0001": {
    "0003": "1984"
  }
}
```

2016-09-06 11:59 UTC, faloi commented
No veo ningún test que pruebe la salida de la memoria... ¿podrás agregar alguno?

2016-09-06 12:28 UTC, susanrosito commented
Es cidrto, no lo testee, tuve inconvenientes ayer y me quedé hasta tarde
para solucionarlos :p

Dale agrego un test sobre eso, tanto el input como el output

El 6 sept. 2016 8:59 a. m., "Federico Aloi" <notifications@github.com>
escribió:

> No veo ningún test que pruebe la salida de la memoria... ¿podrás agregar
> alguno?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Orga-UNQ/qsim/pull/7#issuecomment-244928779>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AEzwUQisrA-OziztaS0H_6kuxxr_RnVPks5qnVW3gaJpZM4Jv1Zh>
> .
>

2016-09-15 20:01 UTC, faloi commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/MultExecutor.scala
> +  var result: JsonOutPut = _
Fijate que hay varias de estas que las podés mover más cerca de la asignación, ya que no necesitás que sean atributos (también vale la recomendación de usar `val` para todo lo que no te interesa que sea mutable).

2016-09-15 20:02 UTC, faloi commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/RunQsimMumuki.scala
> +  multExe.exeInputs(program, arqQ, input)
Me parece más prolijo que el `MultExecutor` devuelva el output como un objeto y hacer el print acá. De esa forma podrías, por ejemplo, testearlo.

2016-09-15 20:05 UTC, faloi commented on src/test/scala/ar/edu/unq/tip/qsim/integracion/mumuki/RefereeQsimMumukiTest.scala
> +        case ex: Throwable             => JsonError(ex.getMessage, "unknown")
¿Por qué todo esto está acá también? Ya está en el código de dominio.

2016-09-15 20:08 UTC, faloi commented on src/test/scala/ar/edu/unq/tip/qsim/integracion/mumuki/RefereeQsimMumukiTest.scala
> +    do {
Uff, no me parece buena idea tener un test tan complejo, cuesta muchísimo entender qué es lo que se está probando. Quizás puedas separarlo en varias pruebas que verifiquen cosas distintas: el tamaño de la salida, el valor de alguna posición en particular, etc.

2016-09-15 20:08 UTC, faloi requested changes

2016-09-15 20:08 UTC, faloi commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/IntegracionMumuki.scala
> +    var tm : java.util.List[JsonInputOk] = gson.fromJson(json, listType)
La variable no es necesaria, podrías sólo retornar la expresión.

2016-09-15 20:08 UTC, faloi commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/MultExecutor.scala
> +    sim = new Simulador()
Podrías directamente declararla acá, no veo la necesidad de que sea un atributo. Además lo haría `val`, porque no queremos que sea mutable la referencia. :grin:

2016-09-15 20:18 UTC, susanrosito commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/RunQsimMumuki.scala
> +  multExe.exeInputs(program, arqQ, input)
Perfecto, ya lo cambio.

2016-09-15 20:25 UTC, susanrosito commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/MultExecutor.scala
> +  var result: JsonOutPut = _
Si, tenes razon. Ya lo cambio

2016-09-15 20:36 UTC, susanrosito commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/MultExecutor.scala
> +    sim = new Simulador()
Si, es verdad. Ya lo cambio.

2016-09-15 20:36 UTC, susanrosito commented on src/test/scala/ar/edu/unq/tip/qsim/integracion/mumuki/RefereeQsimMumukiTest.scala
> +        case ex: Throwable             => JsonError(ex.getMessage, "unknown")
Encare mal los test y quedaron así, sin incorporarle lo nuevo. Ya los cambio.

2016-09-15 20:38 UTC, susanrosito commented on src/test/scala/ar/edu/unq/tip/qsim/integracion/mumuki/RefereeQsimMumukiTest.scala
> +    do {
Dale, mejor, yo en un principio pense en verificar todas las posiciones, para ver si realmente esta devolviendo el estado de la memoria. A mi tampoco me gusto como quedo el test, me parece muy buena idea separarlo en cachitos.

2016-09-15 20:40 UTC, susanrosito commented on src/main/scala/ar/edu/unq/tip/qsim/integracion/mumuki/IntegracionMumuki.scala
> +    var tm : java.util.List[JsonInputOk] = gson.fromJson(json, listType)
Ya lo cambio. Lo acabo de probar y funciona agregando el tipo de retorno en el método.

2016-09-20 19:23 UTC, merged